### ISSUE TITLE
Add checkbox/cookie warning where cookies can be accepted

### ISSUE THREAD

**Issue by HannesBBR** [HannesBBR/PizzaApp#4]

**Comment by HannesBBR** [comment]
https://github.com/Palmabit-IT/angular-cookie-law
http://stackoverflow.com/questions/31316832/any-angular-directive-for-handling-cookie-law-compliance

**Comment by HannesBBR** [comment]
Eerste ziet er wel nice uit, maar geeft precies error alsk et probeer.

**Comment by mathijsrogiers** [comment]
Kheb voor een snelle oplossing gekozen:

https://silktide.com/tools/cookie-consent/download/

Tziet er ng nice uit ook!
