### ISSUE TITLE
Issue when ordering pizza

### ISSUE THREAD

**Issue by HannesBBR** [HannesBBR/PizzaApp#8]
![image](https://cloud.githubusercontent.com/assets/540610/20648838/bdc3894c-b4b1-11e6-93ce-9d9c0e3a376a.png)

**Comment by HannesBBR** [comment]
Zowel als deliverer of als demo user is het hetzelfde probleem

**Comment by mathijsrogiers** [comment]
Waarschijnlijk omdat je niet op https draait? Mijn deployment draait op https (gewoon self-signed cert, en geimporteerd in chrome ook)

**Comment by HannesBBR** [comment]
Aha dat zou goed kunnen, moet ik nog eens checken dan
